name: secure_app
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.7
  device_info_plus: ^9.1.2
  path_provider: ^2.1.1
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.13.1
  image_picker: ^1.0.4
  flutter_dotenv: ^5.2.1
  sqflite: ^2.2.8+4
  path: ^1.8.2
  flutter_secure_storage: ^9.2.2
  local_auth: ^2.3.0
  permission_handler: ^11.3.1
  flutter_jailbreak_detection: ^1.10.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon.jpg"
  min_sdk_android: 23
  web:
    generate: true
    image_path: "assets/launcher_icon.jpg"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/launcher_icon.jpg"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/launcher_icon.jpg"

flutter_native_splash:
  image: assets/launcher_icon.jpg
  color: "#ffffff"
  android_gravity: center

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
